[package]
rust-version.workspace = true
name = "sdkwork-api-deployments-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-deployments application HTTP plane."


[lints]
workspace = true
[lib]
name = "sdkwork_api_deployments_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
serde_json.workspace = true
sdkwork-deploy-database-host.workspace = true
sdkwork-deploy-service-host.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork-intelligence-deploy-service.workspace = true
sdkwork-routes-deploy-app-api.workspace = true
sdkwork-routes-deploy-backend-api.workspace = true
