[package]
rust-version.workspace = true
name = "sdkwork-deploy-service-host"
version.workspace = true
edition.workspace = true


[lints]
workspace = true
[dependencies]
async-trait.workspace = true
hickory-resolver.workspace = true
tokio.workspace = true
tracing.workspace = true
sdkwork-database-id.workspace = true
sdkwork-deploy-core.workspace = true
sdkwork-deploy-contract.workspace = true
sdkwork-deploy-database-host.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork-deploy-drive-port.workspace = true
sdkwork-deploy-content-provider-port.workspace = true
sdkwork-deploy-web-port.workspace = true
sdkwork-intelligence-deploy-repository-sqlx.workspace = true
sdkwork-intelligence-deploy-service.workspace = true
sdkwork-utils-rust.workspace = true
