[package]
rust-version.workspace = true
name = "sdkwork-deploy-web-port"
version.workspace = true
edition.workspace = true


[lints]
workspace = true
[dependencies]
async-trait.workspace = true
serde_json.workspace = true
sdkwork-deploy-contract.workspace = true
sdkwork-deploy-runtime-compiler.workspace = true
sdkwork-webserver-internal-sdk.workspace = true
sdkwork-utils-rust.workspace = true
