[package]
rust-version.workspace = true
name = "sdkwork-deploy-runtime-compiler"
version.workspace = true
edition.workspace = true


[lints]
workspace = true
[dependencies]
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sdkwork-utils-rust.workspace = true
thiserror.workspace = true

[dev-dependencies]
async-trait.workspace = true
sdkwork-knowledgebase-internal-sdk.workspace = true
sdkwork-webserver-contract.workspace = true
sdkwork-webserver-core.workspace = true
sdkwork-webserver-delivery-runtime.workspace = true
sdkwork-webserver-knowledgebase-provider.workspace = true
tokio.workspace = true
