[package]
rust-version.workspace = true
name = "sdkwork-deploy-drive-port"
version.workspace = true
edition.workspace = true


[lints]
workspace = true
[dependencies]
async-trait.workspace = true
sdkwork-deploy-contract.workspace = true
sdkwork-deploy-core.workspace = true
sdkwork-utils-rust.workspace = true
sdkwork-database-id.workspace = true
sdkwork_drive_app_sdk_generated_rust.workspace = true
