[package]
rust-version.workspace = true
name = "sdkwork-deploy-cloud-account-port"
version.workspace = true
edition.workspace = true


[lints]
workspace = true

[dependencies]
async-trait.workspace = true
sqlx.workspace = true
sdkwork-deploy-contract.workspace = true
sdkwork-deploy-core.workspace = true
sdkwork-iam-provider-account-service.workspace = true
sdkwork-utils-rust.workspace = true

[dev-dependencies]
tokio.workspace = true
